name: ob-poc

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "8"

services:

  loki:
    image: grafana/loki:3.6.2
    container_name: loki
    hostname: loki
    restart: always
    ports:
      - "3100:3100" # Loki HTTP
      - "9095:9095" # Loki gRPC
    volumes:
      - "./loki.yaml:/etc/loki/loki-config.yaml"
    command: 
      [ 
        "-config.file=/etc/loki/loki-config.yaml",
        "-config.expand-env=true",
        "-target=all",
      ]
    networks:
      - net_ob
    logging: *default-logging

  tempo:
    image: grafana/tempo:2.9.0
    container_name: tempo
    hostname: tempo
    restart: always
    ports:
      - "3200:3200"  # Tempo API for HTTP query
      - "14318:4318" # OTLP over HTTP
      - "14317:4317" # OTLP over gRPC
      # - "9096:9095"  # Tempo gRPC
    volumes:
      - "./tempo.yaml:/etc/tempo/tempo-config.yaml"
      # - "./mnt_tempo:/var/tempo"
    command:
      [
        "-config.file=/etc/tempo/tempo-config.yaml",
        "-config.expand-env=true",
        "-target=all",
      ]
    networks:
      - net_ob
    logging: *default-logging

  mimir:
    image: grafana/mimir:3.0.2
    container_name: mimir
    hostname: mimir
    restart: always
    ports:
      - "9009:9009"  # Mimir HTTP (Prometheus remote write/query)
      - "9097:9095"  # Mimir gRPC
    volumes:
      - ./mimir.yaml:/etc/mimir/mimir.yaml
    command:
      - -config.file=/etc/mimir/mimir.yaml
      - -target=all
    networks:
      - net_ob
    logging: *default-logging

  alloy:
    image: grafana/alloy:v1.12.1
    container_name: alloy
    hostname: alloy
    restart: always
    ports:
    #   # - "4317:4317"  # OTLP gRPC receiver
      - "4318:4318"  # OTLP HTTP receiver
      - "12345:12345"  # Alloy UI
      - "12347:12347"  # Faro receiver
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=experimental # 啟用 DEBUG 的話必須要有這行
    networks:
      - net_ob
    depends_on:
      - loki
      - tempo
      - mimir
    logging: *default-logging

  grafana:
    image: grafana/grafana:12.3
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - "3001:3000"  # Grafana UI
    volumes:
      - "./grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana_datasources:/etc/grafana/provisioning/datasources"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    networks:
      - net_ob
    depends_on:
      - loki
      - tempo
      - mimir
    logging: *default-logging

networks:
  net_ob:
    name: net_ob
